import { Geist, Geist_Mono, Abril_Fatface } from "next/font/google";
import "./globals.css";
import { TopbarMenu } from "@/components/ui/topbarMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const abril = Abril_Fatface({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-abril",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${abril.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TopbarMenu />
        {children}
      </body>
    </html>
  );
}

export {abril}
